Database.langs = {
	fr: {
			"GET_GOLD": "Vous obtenez 7 Or",
			"GET_GOLD_2": "Vous obtenez 3 Or",
			"GET_GOLD_3": "Vous obtenez 5 Or",
			"PROHIBITED": "Entrée interdite",
			"YEAHHHH": "Yeahhhhh",
			"SPEND": "Je vais passer la journée à enlever les mauvaises \nherbes",
			"HELP_US": "Aides-nous, ma fille a été kidnappée et \nemprisonnée dans les catacombes à l'est du village",
			"WARRIOR": "Je suis une guerrière sans arme. Il me semble \n qu'il y a une épée dans la grotte du village",
			"LEAVE": "Si tu quittes le village, soit vigilant !",
			"CALM": "Le village est calme",
			"BORED": "Je m'ennnuie",
			"COURAGE": "Tu mérites une bonne récompense pour ton courage",
			"MONEY": "Ne dépense pas l'argent donné inutilement !",
			"NEED_SWORD": "Tu as besoin d'une épée avant de quitter le village",
			"SWORD": "Vous recevez une épée",
			"PASS": "Tu peux passer seulement si tu me donnes 15 Or !",
			"GIVE_ME": "Domme moi 15 Or",
			"YOU_LOSE": "Vous perdez 15 Or",
			"TY": "Merci de m'avoir sauvé !"
		},
	en: {
			"GET_GOLD": "You get 7 Gold",
			"GET_GOLD_2": "You get 3 Gold",
			"GET_GOLD_3": "You get 5 Gold",
			"PROHIBITED": "Entry prohibited",
			"YEAHHHH": "Yeahhhhh",
			"SPEND": "I'll spend the day removing weeds",
			"HELP_US": "Help us, my daughter was kidnapped and imprisoned \nin the catacombs to the east of the village",
			"WARRIOR": "I am a warrior without a weapon. It seems \nhe has a sword in a cave in the village",
			"LEAVE": "If you leave the city, be vigilant !",
			"CALM": "The city is calm.",
			"BORED": "I'm bored",
			"COURAGE": "You deserve a good reward for your courage",
			"MONEY": "Not spend money unnecessarily given !",
			"NEED_SWORD": "You need to have a sword before leaving the village",
			"SWORD": "You receive a sword",
			"PASS": "You can pass only if you give me 15 Or !",
			"GIVE_ME": "Give me 15 Gold",
			"YOU_LOSE": "You lose 15 Gold",
			"TY": "Thank you for saving me !",
			"STORE": "Loja - Compra e venda de ítens",
			"BUY": "Want to buy some potions?"

		},
	pt: {
			"GET_GOLD": "Você ganhou 7 Gold",
			"GET_GOLD_2": "Você ganhou 3 Gold",
			"GET_GOLD_3": "Você ganhou 5 Gold",
			"PROHIBITED": "Entrada Proibida.",
			"YEAHHHH": "Olá " + heroQuest.player.name + ".\nGosto de brincar pelo vilarejo, mas não tenho muitos\namigos.",
			"SPEND": "Como vai " + heroQuest.player.name + "?\nVou passar o dia capinando.",
			"HELP_US": "Me ajude, minha filha foi raptada e feita prisioneira \nnas antigas catatumbas ao leste do vilarejo.",
			"WARRIOR": "Olá " + heroQuest.player.name + ".\nDizem que há uma espada em uma caverna \naqui perto do vilarejo.",
			"LEAVE": "Se você sair do vilarejo, tenha cuidado!",
			"CALM": "A cidade está calma.",
			"BORED": "Estou entediado.",
			"COURAGE": "Você vai ajudar a encontrar minha filha certo?\nMerece uma boa recompensa pela sua coragem.",
			"MONEY": "Não gaste esse dinheiro que lhe dei  em bobagens!",
			"NEED_SWORD": "Espere " + heroQuest.player.name + ", você precisa de uma espada\nantes de sair do vilarejo, é perigoso nessas florestas.",
			"SWORD": 'Você recebeu uma espada!\n (Pressione "A" para Atacar)',
			"PASS": "Você só pode passar me dando 15 Gold.",
			"GIVE_ME": "Me dê 15 Gold e poderá passar.",
			"YOU_LOSE": "Você perdeu 15 Gold",
			"YOU_LOSE_10": "Você perdeu 10 Gold",
			"TY": "Obrigado por me salvar " + heroQuest.player.name + "!",
			"STORE": "Loja - Compra e venda de ítens.",
			"BUY": "Desculpe " + heroQuest.player.name +", todo o nosso estoque\nde armas acabou...",
			"HOST": "Você quer se hospedar aqui pela noite? \n Okay, serão 10 gold."

		}
};